import "./globals.css";
import { ClusterProvider } from "@/components/cluster/cluster-data-access";
import { SolanaProvider } from "@/components/solana/solana-provider";
import { UiLayout } from "@/components/ui/ui-layout";
import { ReactQueryProvider } from "./react-query-provider";
import SolFAIProvider from "@/context/solfai/SolFAIProvider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "AiShares",
  description: "Generated by create-solana-dapp",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <SolFAIProvider>
                <UiLayout>{children}</UiLayout>
                <Toaster />
              </SolFAIProvider>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
